# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to Curseforge

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Build action run to download artifacts from'
        required: true


jobs:
  main:
  
    runs-on: ubuntu-latest
    
    steps:


    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        run_number: ${{ inputs.run }}  


    - name: Get Version
      id: version
      run: |
        X=`echo AdvancedBackups-ALL_JARS-*.zip`; X=${X##AdvancedBackups-ALL_JARS-}; X=${X%%.zip}; echo $X
        echo VERSION=$X >> "$GITHUB_OUTPUT"
      

    - name: Extract Jars
      id: extract-jars
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        mv ./AdvancedBackups-ALL_JARS-"$VERSION".zip ./AdvancedBackups-ALL_JARS-dir
        mv ./AdvancedBackups-ALL_JARS-dir/AdvancedBackups-ALL_JARS-"$VERSION".zip .
        unzip ./AdvancedBackups-ALL_JARS-"$VERSION".zip
        rm -r ./AdvancedBackups-ALL_JARS-*


    - name: Upload Forge-1.7.10

      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.7.10-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "4449,Java 8,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.7.10 - ${{ steps.version.outputs.VERSION }}"
    
