# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to Curseforge

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Build action run to download artifacts from'
        required: true

      version:
        type: choice
        description: Which version to push to curseforge.
        required: true
        options: 
        - All
        - Forge 1.7.10
        - Forge 1.12
        - Forge 1.16
        - Forge 1.18
        - Fabric 1.18
        - Forge 1.19.2
        - Forge 1.19.3
        - Fabric 1.19
        - Forge 1.20
        - Fabric 1.20


jobs:
  main:
  
    runs-on: ubuntu-latest
    
    steps:


    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        run_number: ${{ inputs.run }}  


    - name: Get Version
      id: version
      run: |
        X=`echo AdvancedBackups-ALL_JARS-*.zip`; X=${X##AdvancedBackups-ALL_JARS-}; X=${X%%.zip}; echo $X
        echo VERSION=$X >> "$GITHUB_OUTPUT"
      

    - name: Extract Jars
      id: extract-jars
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        mv ./AdvancedBackups-ALL_JARS-"$VERSION".zip ./AdvancedBackups-ALL_JARS-dir
        mv ./AdvancedBackups-ALL_JARS-dir/AdvancedBackups-ALL_JARS-"$VERSION".zip .
        unzip ./AdvancedBackups-ALL_JARS-"$VERSION".zip
        rm -r ./AdvancedBackups-ALL_JARS-*


    - name: Upload Forge-1.7.10

      uses: itsmeow/curseforge-upload@v3
      if: inputs.version == 'Forge 1.7.10' || inputs.version == 'All'
      with:
        file_path: "AdvancedBackups-forge-1.7.10-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "4449,Java 8,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.7.10 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Forge-1.12

      if: inputs.version == 'Forge 1.12' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.12-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "6756,Java 8,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.12 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Forge-1.16

      if: inputs.version == 'Forge 1.16' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.16-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "8203,8134,Java 8,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.16 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Forge-1.18

      if: inputs.version == 'Forge 1.18' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.18-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9008,Java 17,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.18 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Fabric-1.18

      if: inputs.version == 'Fabric 1.18' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-fabric-1.18-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9008,Java 17,Fabric"
        relations: "fabric-api:requiredDependency"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Fabric 1.18 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Forge-1.19.2

      if: inputs.version == 'Forge 1.19.2' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.19.2-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9186,9259,9366,Java 17,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.19.2 - ${{ steps.version.outputs.VERSION }}"
    

    - name: Upload Forge-1.19.3

      if: inputs.version == 'Forge 1.19.3' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.19.3-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9550,9776,Java 17,Forge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.19.3 - ${{ steps.version.outputs.VERSION }}"

        
    - name: Upload Fabric-1.19

      if: inputs.version == 'Fabric 1.19' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-fabric-1.19-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9366,9776,Java 17,Fabric"
        relations: "fabric-api:requiredDependency"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Fabric 1.19 - ${{ steps.version.outputs.VERSION }}"

    - name: Upload Forge-1.20

      if: inputs.version == 'Forge 1.20' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-forge-1.20-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9971,9990,10236,Java 17,Forge,NeoForge"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Forge 1.20 - ${{ steps.version.outputs.VERSION }}"


    - name: Upload Fabric-1.20

      if: inputs.version == 'Fabric 1.20' || inputs.version == 'All'
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "AdvancedBackups-fabric-1.20-${{ steps.version.outputs.VERSION }}.jar"
        game_endpoint: "minecraft"
        game_versions: "9971,9990,10236,Java 17,Fabric"
        project_id: "876284"
        token: "${{ secrets.CURSEFORGE_TOKEN }}"
        changelog: "${{ vars.CHANGELOG }}"
        display_name: "Fabric 1.20 - ${{ steps.version.outputs.VERSION }}"
    
