# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to Curseforge

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Build action run to download artifacts from'
        required: true


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        run_number: ${{ inputs.run }}  

    - name: Extract Jars
      id: extract-jars
      run: |
        mv ./AdvancedBackups-ALL_JARS-*.zip ./AdvancedBackups-ALL_JARS-dir
        mv ./AdvancedBackups-ALL_JARS/AdvancedBackups-ALL_JARS-*.zip .
        unzip ./AdvancedBackups-ALL_JARS-*.zip
        rm -r ./AdvancedBackups-ALL_JARS*

    - name: ls
      if: always()
      run: ls -la
    
