name: Merge Core
on:
  push:
    branches:
      - core
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy core to other versions
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: core
          files: src/main/java/co/uk/mommyheather/advancedbackups/cli src/main/java/co/uk/mommyheather/advancedbackups/core README.md