name: Version Target

on: issue_comment


jobs:
  check-permission:      
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body,'!target') }}
    name: Check permission
    steps:
      # Check for write permission
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `check` step
      - name: Run only if user has sufficient permissions
        if: steps.check.outputs.has-permission
        run: exit 0 #Successful
      - name: Run only if user has NOT sufficient permissions
        if: "! steps.check.outputs.has-permission"
        run: exit 1 #Failed
          


  run-command:      
    name: Run label check
    needs: [check-permission]
    runs-on: ubuntu-latest

    steps:

    - name: Get Version
      id: version
      run: |
        echo ${{ github.event.comment.body }}
        X=`echo ${{ github.event.comment.body }}  | grep -o '!target.*' | awk '{print $2}'`; echo "Target: $X"
        echo "Target $X" >> "$GITHUB_OUTPUT"

    - name : "Create label if it doesn't exist"
      id: create-label
      run: |
        gh label list
